// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: resourcex.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourcexHealthCheckResponse_ServiceStatus int32

const (
	ResourcexHealthCheckResponse_UNKNOWN         ResourcexHealthCheckResponse_ServiceStatus = 0
	ResourcexHealthCheckResponse_SERVING         ResourcexHealthCheckResponse_ServiceStatus = 1
	ResourcexHealthCheckResponse_NOT_SERVING     ResourcexHealthCheckResponse_ServiceStatus = 2
	ResourcexHealthCheckResponse_SERVICE_UNKNOWN ResourcexHealthCheckResponse_ServiceStatus = 3
)

// Enum value maps for ResourcexHealthCheckResponse_ServiceStatus.
var (
	ResourcexHealthCheckResponse_ServiceStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	ResourcexHealthCheckResponse_ServiceStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x ResourcexHealthCheckResponse_ServiceStatus) Enum() *ResourcexHealthCheckResponse_ServiceStatus {
	p := new(ResourcexHealthCheckResponse_ServiceStatus)
	*p = x
	return p
}

func (x ResourcexHealthCheckResponse_ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourcexHealthCheckResponse_ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_resourcex_proto_enumTypes[0].Descriptor()
}

func (ResourcexHealthCheckResponse_ServiceStatus) Type() protoreflect.EnumType {
	return &file_resourcex_proto_enumTypes[0]
}

func (x ResourcexHealthCheckResponse_ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourcexHealthCheckResponse_ServiceStatus.Descriptor instead.
func (ResourcexHealthCheckResponse_ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_resourcex_proto_rawDescGZIP(), []int{2, 0}
}

type BaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_resourcex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourcex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_resourcex_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResourcexHealthCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *ResourcexHealthCheckRequest) Reset() {
	*x = ResourcexHealthCheckRequest{}
	mi := &file_resourcex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcexHealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcexHealthCheckRequest) ProtoMessage() {}

func (x *ResourcexHealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourcex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcexHealthCheckRequest.ProtoReflect.Descriptor instead.
func (*ResourcexHealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_resourcex_proto_rawDescGZIP(), []int{1}
}

func (x *ResourcexHealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type ResourcexHealthCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status ResourcexHealthCheckResponse_ServiceStatus `protobuf:"varint,1,opt,name=status,proto3,enum=proto.ResourcexHealthCheckResponse_ServiceStatus" json:"status,omitempty"`
}

func (x *ResourcexHealthCheckResponse) Reset() {
	*x = ResourcexHealthCheckResponse{}
	mi := &file_resourcex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcexHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcexHealthCheckResponse) ProtoMessage() {}

func (x *ResourcexHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourcex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcexHealthCheckResponse.ProtoReflect.Descriptor instead.
func (*ResourcexHealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_resourcex_proto_rawDescGZIP(), []int{2}
}

func (x *ResourcexHealthCheckResponse) GetStatus() ResourcexHealthCheckResponse_ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ResourcexHealthCheckResponse_UNKNOWN
}

type ResourcexUploadFileChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Chunk:
	//
	//	*ResourcexUploadFileChunk_Metadata
	//	*ResourcexUploadFileChunk_Data
	Chunk isResourcexUploadFileChunk_Chunk `protobuf_oneof:"chunk"`
}

func (x *ResourcexUploadFileChunk) Reset() {
	*x = ResourcexUploadFileChunk{}
	mi := &file_resourcex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcexUploadFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcexUploadFileChunk) ProtoMessage() {}

func (x *ResourcexUploadFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_resourcex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcexUploadFileChunk.ProtoReflect.Descriptor instead.
func (*ResourcexUploadFileChunk) Descriptor() ([]byte, []int) {
	return file_resourcex_proto_rawDescGZIP(), []int{3}
}

func (m *ResourcexUploadFileChunk) GetChunk() isResourcexUploadFileChunk_Chunk {
	if m != nil {
		return m.Chunk
	}
	return nil
}

func (x *ResourcexUploadFileChunk) GetMetadata() *ResourcexUploadFileMetadata {
	if x, ok := x.GetChunk().(*ResourcexUploadFileChunk_Metadata); ok {
		return x.Metadata
	}
	return nil
}

func (x *ResourcexUploadFileChunk) GetData() []byte {
	if x, ok := x.GetChunk().(*ResourcexUploadFileChunk_Data); ok {
		return x.Data
	}
	return nil
}

type isResourcexUploadFileChunk_Chunk interface {
	isResourcexUploadFileChunk_Chunk()
}

type ResourcexUploadFileChunk_Metadata struct {
	// 文件元数据（文件名、MD5等）
	Metadata *ResourcexUploadFileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type ResourcexUploadFileChunk_Data struct {
	// 文件数据块
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*ResourcexUploadFileChunk_Metadata) isResourcexUploadFileChunk_Chunk() {}

func (*ResourcexUploadFileChunk_Data) isResourcexUploadFileChunk_Chunk() {}

type ResourcexUploadFileMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 发送此文件的app
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// 此文件的标签，通常用于区分业务
	Tag string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	// 文件的所有者
	Owner string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	// 租户id
	TenantId string `protobuf:"bytes,4,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	// 所对应的空间id
	SpaceObjectId string `protobuf:"bytes,5,opt,name=spaceObjectId,proto3" json:"spaceObjectId,omitempty"`
	// 存储的文件路径
	FullFilePath string `protobuf:"bytes,6,opt,name=fullFilePath,proto3" json:"fullFilePath,omitempty"`
	// 文件的MD5哈希值
	FileMd5 string `protobuf:"bytes,7,opt,name=fileMd5,proto3" json:"fileMd5,omitempty"`
}

func (x *ResourcexUploadFileMetadata) Reset() {
	*x = ResourcexUploadFileMetadata{}
	mi := &file_resourcex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcexUploadFileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcexUploadFileMetadata) ProtoMessage() {}

func (x *ResourcexUploadFileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_resourcex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcexUploadFileMetadata.ProtoReflect.Descriptor instead.
func (*ResourcexUploadFileMetadata) Descriptor() ([]byte, []int) {
	return file_resourcex_proto_rawDescGZIP(), []int{4}
}

func (x *ResourcexUploadFileMetadata) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ResourcexUploadFileMetadata) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ResourcexUploadFileMetadata) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ResourcexUploadFileMetadata) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ResourcexUploadFileMetadata) GetSpaceObjectId() string {
	if x != nil {
		return x.SpaceObjectId
	}
	return ""
}

func (x *ResourcexUploadFileMetadata) GetFullFilePath() string {
	if x != nil {
		return x.FullFilePath
	}
	return ""
}

func (x *ResourcexUploadFileMetadata) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

type UploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 文件对象id
	FileObjectId string `protobuf:"bytes,2,opt,name=fileObjectId,proto3" json:"fileObjectId,omitempty"`
	// 文件名
	FileName string `protobuf:"bytes,3,opt,name=fileName,proto3" json:"fileName,omitempty"`
	// 文件下载url
	FileUrl string `protobuf:"bytes,4,opt,name=fileUrl,proto3" json:"fileUrl,omitempty"`
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_resourcex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourcex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_resourcex_proto_rawDescGZIP(), []int{5}
}

func (x *UploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadResponse) GetFileObjectId() string {
	if x != nil {
		return x.FileObjectId
	}
	return ""
}

func (x *UploadResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadResponse) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

var File_resourcex_proto protoreflect.FileDescriptor

var file_resourcex_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x37, 0x0a, 0x1b, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x78, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0xba, 0x01, 0x0a, 0x1c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x78, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x49, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x78, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4f, 0x0a, 0x0d, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x52,
	0x56, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x54, 0x5f, 0x53, 0x45,
	0x52, 0x56, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x45, 0x52, 0x56, 0x49,
	0x43, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x22, 0x7b, 0x0a, 0x18,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x78, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x40, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x78, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x00,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x42, 0x07, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0xd7, 0x01, 0x0a, 0x1b, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x78, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x24, 0x0a, 0x0d, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x75, 0x6c, 0x6c, 0x46, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x75, 0x6c,
	0x6c, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x6c,
	0x65, 0x4d, 0x64, 0x35, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65,
	0x4d, 0x64, 0x35, 0x22, 0x84, 0x01, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x22, 0x0a, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x32, 0xbd, 0x01, 0x0a, 0x09, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x78, 0x12, 0x5f, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x78, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x78, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x78, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x13, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x78, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x78, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resourcex_proto_rawDescOnce sync.Once
	file_resourcex_proto_rawDescData = file_resourcex_proto_rawDesc
)

func file_resourcex_proto_rawDescGZIP() []byte {
	file_resourcex_proto_rawDescOnce.Do(func() {
		file_resourcex_proto_rawDescData = protoimpl.X.CompressGZIP(file_resourcex_proto_rawDescData)
	})
	return file_resourcex_proto_rawDescData
}

var file_resourcex_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resourcex_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_resourcex_proto_goTypes = []any{
	(ResourcexHealthCheckResponse_ServiceStatus)(0), // 0: proto.ResourcexHealthCheckResponse.ServiceStatus
	(*BaseResponse)(nil),                            // 1: proto.BaseResponse
	(*ResourcexHealthCheckRequest)(nil),             // 2: proto.ResourcexHealthCheckRequest
	(*ResourcexHealthCheckResponse)(nil),            // 3: proto.ResourcexHealthCheckResponse
	(*ResourcexUploadFileChunk)(nil),                // 4: proto.ResourcexUploadFileChunk
	(*ResourcexUploadFileMetadata)(nil),             // 5: proto.ResourcexUploadFileMetadata
	(*UploadResponse)(nil),                          // 6: proto.UploadResponse
}
var file_resourcex_proto_depIdxs = []int32{
	0, // 0: proto.ResourcexHealthCheckResponse.status:type_name -> proto.ResourcexHealthCheckResponse.ServiceStatus
	5, // 1: proto.ResourcexUploadFileChunk.metadata:type_name -> proto.ResourcexUploadFileMetadata
	2, // 2: proto.Resourcex.ResourcexHealthCheck:input_type -> proto.ResourcexHealthCheckRequest
	4, // 3: proto.Resourcex.ResourcexUploadFile:input_type -> proto.ResourcexUploadFileChunk
	3, // 4: proto.Resourcex.ResourcexHealthCheck:output_type -> proto.ResourcexHealthCheckResponse
	6, // 5: proto.Resourcex.ResourcexUploadFile:output_type -> proto.UploadResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_resourcex_proto_init() }
func file_resourcex_proto_init() {
	if File_resourcex_proto != nil {
		return
	}
	file_resourcex_proto_msgTypes[3].OneofWrappers = []any{
		(*ResourcexUploadFileChunk_Metadata)(nil),
		(*ResourcexUploadFileChunk_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resourcex_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resourcex_proto_goTypes,
		DependencyIndexes: file_resourcex_proto_depIdxs,
		EnumInfos:         file_resourcex_proto_enumTypes,
		MessageInfos:      file_resourcex_proto_msgTypes,
	}.Build()
	File_resourcex_proto = out.File
	file_resourcex_proto_rawDesc = nil
	file_resourcex_proto_goTypes = nil
	file_resourcex_proto_depIdxs = nil
}
